/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/dataset/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate */
        post: operations["generate_api_v1_dataset_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Customers */
        get: operations["list_customers_api_v1_customers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{customer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Customer */
        get: operations["get_customer_api_v1_customers__customer_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{customer_id}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Transactions */
        get: operations["get_transactions_api_v1_customers__customer_id__transactions_get"];
        put?: never;
        /**
         * Create Transaction
         * @description Append a transaction.
         *
         *     Features are recomputed on read rather than cached here, so a new
         *     transaction is reflected in the next features/simulate/recommend call
         *     without an explicit invalidation step.
         */
        post: operations["create_transaction_api_v1_customers__customer_id__transactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{customer_id}/features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Features */
        get: operations["get_features_api_v1_customers__customer_id__features_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{customer_id}/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate */
        post: operations["simulate_api_v1_customers__customer_id__simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{customer_id}/distress-risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Distress Risk */
        get: operations["distress_risk_api_v1_customers__customer_id__distress_risk_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{customer_id}/anomalies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Anomalies */
        get: operations["get_anomalies_api_v1_customers__customer_id__anomalies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{customer_id}/recommend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Recommendation */
        post: operations["create_recommendation_api_v1_customers__customer_id__recommend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{customer_id}/matching-products/{recommendation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Matching Products
         * @description Top 3 real bank products matching a recommendation (spec addendum).
         *
         *     Every product is priced and re-checked through the safety gate
         *     individually, and carries its own provenance note so nothing here is
         *     presented as a verified live quote.
         */
        get: operations["matching_products_api_v1_customers__customer_id__matching_products__recommendation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{customer_id}/explain/{recommendation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Explain
         * @description Attributions for a recommendation, including a vetoed one.
         *
         *     Spec Section 10.7 treats explanation as a right, so this endpoint answers
         *     for declined recommendations too — and for those it reports which
         *     constraint blocked the decision and the values that triggered it, which is
         *     the part a customer actually needs in order to act.
         */
        get: operations["explain_api_v1_customers__customer_id__explain__recommendation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/consent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grant Consent */
        post: operations["grant_consent_api_v1_consent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{customer_id}/consent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Consent */
        get: operations["list_consent_api_v1_customers__customer_id__consent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/consent/{consent_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke Consent */
        post: operations["revoke_consent_api_v1_consent__consent_id__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/{customer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Audit Log */
        get: operations["get_audit_log_api_v1_audit__customer_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/onboarding/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start */
        post: operations["start_api_v1_onboarding_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/onboarding/{session_id}/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Message */
        post: operations["message_api_v1_onboarding__session_id__message_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/onboarding/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_v1_onboarding__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{customer_id}/enquire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enquire
         * @description Answer "can I afford this?" for a product the customer asked about.
         *
         *     The same safety gate applies as to anything the optimizer proposes — a
         *     customer who asks for credit does not get a weaker check than one who was
         *     offered it. When the answer is no, the response carries the largest amount
         *     that would pass, so the customer is told what *is* affordable rather than
         *     left to guess.
         */
        post: operations["enquire_api_v1_customers__customer_id__enquire_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnomalyItem */
        AnomalyItem: {
            /** Transaction Id */
            transaction_id: string;
            /** Txn Date */
            txn_date: string;
            /** Amount */
            amount: number;
            /** Type */
            type: string;
            /** Category */
            category: string;
            /** Merchant */
            merchant: string;
            /** Detection Method */
            detection_method: string;
            /** Anomaly Score */
            anomaly_score: number;
            /** Confidence */
            confidence: number;
            /** Features */
            features: {
                [key: string]: number | null;
            };
            /**
             * Injected Tag
             * @description Ground-truth tag from the synthetic generator; validation aid only.
             */
            injected_tag?: string | null;
        };
        /** AnomalyListResponse */
        AnomalyListResponse: {
            /** Anomalies */
            anomalies: components["schemas"]["AnomalyItem"][];
            /** Total */
            total: number;
        };
        /** Attribution */
        Attribution: {
            /** Feature */
            feature: string;
            /** Value */
            value: number | string | null;
            /** Shap */
            shap: number;
            /** Direction */
            direction: string;
        };
        /** AuditLogItem */
        AuditLogItem: {
            /** Id */
            id: string;
            /** Action */
            action: string;
            /** Module */
            module: string;
            /** Input Hash */
            input_hash: string;
            /** Output Summary */
            output_summary: Record<string, never>;
            /** Timestamp */
            timestamp: string;
        };
        /** AuditLogResponse */
        AuditLogResponse: {
            /** Customer Id */
            customer_id: string;
            /** Logs */
            logs: components["schemas"]["AuditLogItem"][];
            /** Total */
            total: number;
        };
        /** BankProductMatch */
        BankProductMatch: {
            /** Bank Name */
            bank_name: string;
            /** Product Name */
            product_name: string;
            /** Product Type */
            product_type: string;
            /** Amount */
            amount: number;
            /** Tenure Months */
            tenure_months: number | null;
            interest_rate_band: components["schemas"]["InterestRateBand"];
            /** Monthly Cost */
            monthly_cost: number;
            /** Total Interest At Min Rate */
            total_interest_at_min_rate: number;
            /** Processing Fee Pct */
            processing_fee_pct: number | null;
            /** Annual Fee */
            annual_fee: number | null;
            /** Post Dbr */
            post_dbr: number;
            /** Post P Shortfall 12M */
            post_p_shortfall_12m: number;
            /** Post Runway Months */
            post_runway_months: number;
            /** Passes Safety Gate */
            passes_safety_gate: boolean;
            /** Veto Reason */
            veto_reason: string | null;
            /** Constraints Failed */
            constraints_failed: string[];
            /** Eligibility Notes */
            eligibility_notes: string;
            /**
             * Source Note
             * @description Provenance; these are illustrative bands, not live quotes.
             */
            source_note: string;
            /** Source Url */
            source_url: string | null;
            /** Last Verified Date */
            last_verified_date: string;
        };
        /** CBSComponentsOut */
        CBSComponentsOut: {
            /** Need Match */
            need_match: number;
            /** Affordability Delta */
            affordability_delta: number;
            /** Risk Reduction */
            risk_reduction: number;
            /** Life Stage Align */
            life_stage_align: number;
            /** Distress Delta */
            distress_delta: number;
        };
        /** ConfidenceInterval */
        ConfidenceInterval: {
            /** Cbs Low */
            cbs_low: number | null;
            /** Cbs High */
            cbs_high: number | null;
            /** Method */
            method: string;
            /** Ci Width Ratio */
            ci_width_ratio: number | null;
        };
        /** ConsentCreated */
        ConsentCreated: {
            /** Id */
            id: string;
            /** Customer Id */
            customer_id: string;
            /** Scope */
            scope: string;
            /** Granted */
            granted: boolean;
            /** Granted At */
            granted_at: string | null;
            /** Revoked At */
            revoked_at: string | null;
            /** Purpose */
            purpose: string;
        };
        /** ConsentListResponse */
        ConsentListResponse: {
            /** Customer Id */
            customer_id: string;
            /** Consent Records */
            consent_records: components["schemas"]["ConsentRecordOut"][];
        };
        /** ConsentRecordOut */
        ConsentRecordOut: {
            /** Id */
            id: string;
            /** Scope */
            scope: string;
            /** Granted */
            granted: boolean;
            /** Granted At */
            granted_at: string | null;
            /** Revoked At */
            revoked_at: string | null;
            /** Purpose */
            purpose: string;
            /** Active */
            active: boolean;
        };
        /** ConsentRequest */
        ConsentRequest: {
            /**
             * Customer Id
             * Format: uuid
             */
            customer_id: string;
            /** Scope */
            scope: string;
            /** Granted */
            granted: boolean;
            /** Purpose */
            purpose: string;
        };
        /** ConsentRevoked */
        ConsentRevoked: {
            /** Id */
            id: string;
            /** Scope */
            scope: string;
            /** Granted */
            granted: boolean;
            /** Revoked At */
            revoked_at: string;
            /** Active */
            active: boolean;
        };
        /** CounterOffer */
        CounterOffer: {
            /** Amount */
            amount?: number | null;
            /** Tenure Months */
            tenure_months?: number | null;
            /** Monthly Cost */
            monthly_cost?: number | null;
            /** Post Dbr */
            post_dbr?: number | null;
            /** Post P Shortfall 12M */
            post_p_shortfall_12m?: number | null;
            /** Post Runway Months */
            post_runway_months?: number | null;
            /** Passes */
            passes?: boolean | null;
            /** Veto Reason */
            veto_reason?: string | null;
            /** Constraints Passed */
            constraints_passed?: string[] | null;
            /** Constraints Failed */
            constraints_failed?: string[] | null;
            /** Blocking Constraints */
            blocking_constraints?: string[] | null;
            /** Blocking Reason */
            blocking_reason?: string | null;
            /** Note */
            note: string;
        };
        /** CustomerDetail */
        CustomerDetail: {
            /** Id */
            id: string;
            /** External Id */
            external_id: string | null;
            /** Persona */
            persona: string;
            /** Name */
            name: string;
            /** Age */
            age: number;
            /** City */
            city: string;
            /** State */
            state: string;
            /** Preferred Language */
            preferred_language: string;
            /** Monthly Income Mean */
            monthly_income_mean: number;
            /** Monthly Income Std */
            monthly_income_std: number;
            /** Liquid Savings */
            liquid_savings: number;
            /** Credit Limit */
            credit_limit: number | null;
            /** Credit Outstanding */
            credit_outstanding: number | null;
            /** Life Stage */
            life_stage: string;
            /** Distress State */
            distress_state: boolean;
            /** Distress Event Month */
            distress_event_month: number | null;
            /** Distress Event Type */
            distress_event_type: string | null;
            /** Created At */
            created_at: string | null;
        };
        /** CustomerListResponse */
        CustomerListResponse: {
            /** Customers */
            customers: components["schemas"]["CustomerSummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** CustomerSummary */
        CustomerSummary: {
            /** Id */
            id: string;
            /** Persona */
            persona: string;
            /** Name */
            name: string;
            /** Age */
            age: number;
            /** City */
            city: string;
            /** Monthly Income Mean */
            monthly_income_mean: number;
            /** Dbr */
            dbr: number | null;
            /** Liquidity Runway */
            liquidity_runway: number | null;
            /** Distress State */
            distress_state: boolean;
            /** Life Stage */
            life_stage: string;
        };
        /** DatasetGenerateResponse */
        DatasetGenerateResponse: {
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
            /** Estimated Customers */
            estimated_customers: number;
            /** Estimated Transactions */
            estimated_transactions: number;
        };
        /** DistressRiskResponse */
        DistressRiskResponse: {
            /** Customer Id */
            customer_id: string;
            /** Distress Probability 12M */
            distress_probability_12m: number;
            /**
             * Survival Function
             * @description Keyed by month index
             */
            survival_function: {
                [key: string]: number;
            };
            /** Hazard Ratios */
            hazard_ratios: {
                [key: string]: number;
            };
            /** Median Survival Time Months */
            median_survival_time_months: number | null;
            /** Primary Model */
            primary_model: string;
            /** Concordance Index */
            concordance_index: number;
            fallback_model: components["schemas"]["FallbackModelSummary"];
            /** Model Version */
            model_version: string;
        };
        /** EnquiryAssessment */
        EnquiryAssessment: {
            /** Amount */
            amount: number;
            /** Tenure Months */
            tenure_months: number | null;
            /** Monthly Cost */
            monthly_cost: number;
            /** Post Dbr */
            post_dbr: number;
            /** Post P Shortfall 12M */
            post_p_shortfall_12m: number;
            /** Post Runway Months */
            post_runway_months: number;
            /** Passes */
            passes: boolean;
            /** Veto Reason */
            veto_reason: string | null;
            /** Constraints Passed */
            constraints_passed: string[];
            /** Constraints Failed */
            constraints_failed: string[];
        };
        /** EnquiryBaseline */
        EnquiryBaseline: {
            /** Dbr */
            dbr: number | null;
            /** P Shortfall 12M */
            p_shortfall_12m: number;
            /** Expected Runway */
            expected_runway: number;
            /** Liquidity Runway Months */
            liquidity_runway_months: number | null;
        };
        /** EnquiryRequest */
        EnquiryRequest: {
            /** Product Type */
            product_type: string;
            /** Amount */
            amount: number;
            /** Tenure Months */
            tenure_months?: number | null;
        };
        /** EnquiryRequested */
        EnquiryRequested: {
            /** Product Type */
            product_type: string;
            /** Amount */
            amount: number;
            /** Tenure Months */
            tenure_months: number | null;
        };
        /** EnquiryResponse */
        EnquiryResponse: {
            /** Customer Id */
            customer_id: string;
            requested: components["schemas"]["EnquiryRequested"];
            /**
             * Verdict
             * @description affordable | declined
             */
            verdict: string;
            assessment: components["schemas"]["EnquiryAssessment"];
            baseline: components["schemas"]["EnquiryBaseline"];
            /** Distress Probability 12M */
            distress_probability_12m: number;
            counter_offer: components["schemas"]["CounterOffer"] | null;
            /** Matching Products */
            matching_products: components["schemas"]["BankProductMatch"][];
            /** Matching Products Note */
            matching_products_note?: string | null;
        };
        /** ExplainResponse */
        ExplainResponse: {
            /** Customer Id */
            customer_id: string;
            /** Recommendation Id */
            recommendation_id: string;
            /** Product Type */
            product_type: string;
            /** Status */
            status: string;
            /** Shap Values */
            shap_values: components["schemas"]["Attribution"][];
            /** Need Match Attribution */
            need_match_attribution: components["schemas"]["Attribution"][];
            /** Model Used */
            model_used: string;
            /** Explanation */
            explanation: string;
            /** Veto Reason */
            veto_reason: string | null;
            /** Constraints Failed */
            constraints_failed: string[] | null;
            /** Confidence Level */
            confidence_level: string;
            /** Confidence Interval */
            confidence_interval: Record<string, never> | null;
        };
        /** FallbackModelSummary */
        FallbackModelSummary: {
            /** Name */
            name: string;
            /** Distress Probability 12M */
            distress_probability_12m: number;
            /** Concordance Index */
            concordance_index: number;
        };
        /** FeaturesResponse */
        FeaturesResponse: {
            /** Customer Id */
            customer_id: string;
            /** Snapshot Date */
            snapshot_date: string;
            /**
             * Features
             * @description Computed feature vector; see app/features for definitions.
             */
            features: {
                [key: string]: number | null;
            };
            /** Model Version */
            model_version: string;
        };
        /** GenerateRequest */
        GenerateRequest: {
            /**
             * N Customers
             * @default 1000
             */
            n_customers: number;
            /**
             * Seed
             * @default 42
             */
            seed: number;
            /**
             * Clear Existing
             * @default true
             */
            clear_existing: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Database */
            database: string;
            /** Model Version */
            model_version: string;
            models: components["schemas"]["ModelWarmupStatus"];
            /** Timestamp */
            timestamp: string;
        };
        /** InterestRateBand */
        InterestRateBand: {
            /** Min */
            min: number;
            /** Max */
            max: number;
        };
        /** MatchingProductsResponse */
        MatchingProductsResponse: {
            /** Customer Id */
            customer_id: string;
            /** Recommendation Id */
            recommendation_id: string;
            /** Product Type */
            product_type: string;
            /** Amount */
            amount?: number | null;
            /** Tenure Months */
            tenure_months?: number | null;
            /** Matching Products */
            matching_products: components["schemas"]["BankProductMatch"][];
            /** Disclaimer */
            disclaimer?: string | null;
            /** Note */
            note?: string | null;
        };
        /** MessageRequest */
        MessageRequest: {
            /** Message */
            message: string;
        };
        /** ModelWarmupStatus */
        ModelWarmupStatus: {
            /**
             * Status
             * @description cold | warming | warm | failed | skipped_no_data
             */
            status: string;
            /** Seconds */
            seconds?: number | null;
            /** Error */
            error?: string | null;
        };
        /** NewTransaction */
        NewTransaction: {
            /**
             * Txn Date
             * Format: date
             */
            txn_date: string;
            /** Txn Time */
            txn_time?: string | null;
            /**
             * Amount
             * @description Always positive; direction is carried by `type`
             */
            amount: number;
            /**
             * Type
             * @enum {string}
             */
            type: "credit" | "debit";
            /** Category */
            category: string;
            /** Merchant */
            merchant: string;
            /** Description */
            description?: string | null;
            /**
             * Is Recurring
             * @default false
             */
            is_recurring: boolean;
        };
        /** OnboardingMessageResponse */
        OnboardingMessageResponse: {
            /** Step */
            step: string;
            /** Message */
            message: string;
            /** Progress */
            progress: number;
            /** Accepted */
            accepted: boolean;
            /** Attempts */
            attempts?: number | null;
            /** Review */
            review?: Record<string, never> | null;
        };
        /** OnboardingStartResponse */
        OnboardingStartResponse: {
            /** Session Id */
            session_id: string;
            /** Step */
            step: string;
            /** Message */
            message: string;
            /** Progress */
            progress: number;
        };
        /** OnboardingStateResponse */
        OnboardingStateResponse: {
            /** Session Id */
            session_id: string;
            /** Language */
            language: string;
            /** Step */
            step: string;
            /** Progress */
            progress: number;
            /** Collected */
            collected: Record<string, never>;
        };
        /** RecommendRequest */
        RecommendRequest: {
            /**
             * Language
             * @default hi
             */
            language: string;
            /**
             * Include Llm Explanation
             * @default false
             */
            include_llm_explanation: boolean;
        };
        /** RecommendationResponse */
        RecommendationResponse: {
            /** Recommendation Id */
            recommendation_id?: string | null;
            /** Customer Id */
            customer_id: string;
            /** Product Type */
            product_type: string;
            /** Amount */
            amount: number | null;
            /** Tenure Months */
            tenure_months: number | null;
            /** Monthly Cost */
            monthly_cost: number | null;
            /** Cbs Score */
            cbs_score: number;
            cbs_components: components["schemas"]["CBSComponentsOut"];
            /** Constraints Passed */
            constraints_passed: string[];
            /** Constraints Failed */
            constraints_failed: string[];
            simulation_summary: components["schemas"]["SimulationSummary"];
            /** Distress Probability */
            distress_probability: number;
            /** Distress State */
            distress_state: boolean;
            /** Max Anomaly Score */
            max_anomaly_score: number;
            /**
             * Status
             * @description recommended | no_action | vetoed
             */
            status: string;
            /** Veto Reason */
            veto_reason: string | null;
            /** Language */
            language: string;
            /** Candidates Evaluated */
            candidates_evaluated: number;
            /** Candidates Feasible */
            candidates_feasible: number;
            /** Confidence Level */
            confidence_level: string;
            confidence_interval: components["schemas"]["ConfidenceInterval"];
            /** Shap Values */
            shap_values: components["schemas"]["Attribution"][];
            /** Need Match Attribution */
            need_match_attribution: components["schemas"]["Attribution"][];
            /** Explanation */
            explanation: string;
            /** Llm Explanation */
            llm_explanation: string | null;
            /** Llm Status */
            llm_status: string | null;
        };
        /** SimulateRequest */
        SimulateRequest: {
            /**
             * Scenarios
             * @default [
             *       "baseline"
             *     ]
             */
            scenarios: string[];
            /** Loan Amount */
            loan_amount?: number | null;
            /** Loan Tenure Months */
            loan_tenure_months?: number | null;
            /** Loan Interest Rate */
            loan_interest_rate?: number | null;
            /**
             * N Paths
             * @default 1000
             */
            n_paths: number;
            /**
             * Months Projected
             * @default 12
             */
            months_projected: number;
            /**
             * Method
             * @default auto
             */
            method: string;
        };
        /** SimulateResponse */
        SimulateResponse: {
            /** Customer Id */
            customer_id: string;
            /** Simulation Id */
            simulation_id: string;
            /** Scenarios */
            scenarios: {
                [key: string]: components["schemas"]["SimulationScenario"];
            };
            /** Confidence Bands */
            confidence_bands: {
                [key: string]: {
                    [key: string]: {
                        [key: string]: number;
                    };
                };
            };
        };
        /** SimulationScenario */
        SimulationScenario: {
            /** P Shortfall 12M */
            p_shortfall_12m: number;
            /** Expected Liquidity */
            expected_liquidity: {
                [key: string]: number;
            };
            /** Liquidity Percentiles */
            liquidity_percentiles: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** Expected Runway */
            expected_runway: number;
            /** Parameters */
            parameters: Record<string, never>;
        };
        /** SimulationSummary */
        SimulationSummary: {
            /** P Shortfall 12M */
            p_shortfall_12m: number;
            /** Expected Runway */
            expected_runway: number;
            /** P5 Liquidity 12M */
            p5_liquidity_12m: number | null;
            /** P95 Liquidity 12M */
            p95_liquidity_12m: number | null;
        };
        /** StartRequest */
        StartRequest: {
            /**
             * Language
             * @default hi
             */
            language: string;
            /** Customer Name */
            customer_name?: string | null;
        };
        /** TransactionCreated */
        TransactionCreated: {
            /** Id */
            id: string;
            /** Customer Id */
            customer_id: string;
            /** Txn Date */
            txn_date: string;
            /** Txn Time */
            txn_time: string | null;
            /** Amount */
            amount: number;
            /** Type */
            type: string;
            /** Category */
            category: string;
            /** Merchant */
            merchant: string;
            /** Description */
            description: string | null;
            /** Is Recurring */
            is_recurring: boolean;
        };
        /** TransactionItem */
        TransactionItem: {
            /** Id */
            id: string;
            /** Txn Date */
            txn_date: string;
            /** Txn Time */
            txn_time: string | null;
            /** Amount */
            amount: number;
            /** Type */
            type: string;
            /** Category */
            category: string;
            /** Merchant */
            merchant: string;
            /** Is Recurring */
            is_recurring: boolean;
            /** Is Anomaly */
            is_anomaly: boolean;
        };
        /** TransactionListResponse */
        TransactionListResponse: {
            /** Transactions */
            transactions: components["schemas"]["TransactionItem"][];
            /** Total */
            total: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    generate_api_v1_dataset_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetGenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_customers_api_v1_customers_get: {
        parameters: {
            query?: {
                persona?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_customer_api_v1_customers__customer_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transactions_api_v1_customers__customer_id__transactions_get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
                category?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_transaction_api_v1_customers__customer_id__transactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewTransaction"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_features_api_v1_customers__customer_id__features_get: {
        parameters: {
            query?: {
                snapshot_date?: string | null;
            };
            header?: never;
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeaturesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_api_v1_customers__customer_id__simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    distress_risk_api_v1_customers__customer_id__distress_risk_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DistressRiskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_anomalies_api_v1_customers__customer_id__anomalies_get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
                min_score?: number;
                limit?: number;
                persist?: boolean;
            };
            header?: never;
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnomalyListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_recommendation_api_v1_customers__customer_id__recommend_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    matching_products_api_v1_customers__customer_id__matching_products__recommendation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: string;
                recommendation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchingProductsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_api_v1_customers__customer_id__explain__recommendation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: string;
                recommendation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    grant_consent_api_v1_consent_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_consent_api_v1_customers__customer_id__consent_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_consent_api_v1_consent__consent_id__revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                consent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentRevoked"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audit_log_api_v1_audit__customer_id__get: {
        parameters: {
            query?: {
                action?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_api_v1_onboarding_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    message_api_v1_onboarding__session_id__message_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingMessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_v1_onboarding__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enquire_api_v1_customers__customer_id__enquire_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnquiryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnquiryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
