"""initial schema

Revision ID: 980cd04c5ba9
Revises: 
Create Date: 2026-09-12 14:10:29.447019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '980cd04c5ba9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_products',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('bank_name', sa.String(length=80), nullable=False),
    sa.Column('product_type', sa.String(length=30), nullable=False),
    sa.Column('product_name', sa.String(length=150), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('interest_rate_min', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('interest_rate_max', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tenure_options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processing_fee_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('annual_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('eligibility_notes', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_note', sa.Text(), nullable=False),
    sa.Column('last_verified_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("product_type IN ('personal_loan','credit_card','term_insurance','mutual_fund_sip')", name='ck_bank_products_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bank_products_type', 'bank_products', ['product_type'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=True),
    sa.Column('persona', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('monthly_income_mean', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monthly_income_std', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('liquid_savings', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('credit_outstanding', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('life_stage', sa.String(length=20), nullable=False),
    sa.Column('distress_state', sa.Boolean(), nullable=False),
    sa.Column('distress_event_month', sa.Integer(), nullable=True),
    sa.Column('distress_event_type', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index('idx_customers_persona', 'customers', ['persona'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('module', sa.String(length=30), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('output_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_customer_ts', 'audit_logs', ['customer_id', 'timestamp'], unique=False)
    op.create_table('consent_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(length=30), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("scope IN ('transaction_analysis','credit_assessment','product_recommendation','marketing','anomaly_monitoring')", name='ck_consent_scope'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_consent_customer_scope', 'consent_records', ['customer_id', 'scope'], unique=False)
    op.create_table('feature_snapshots',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_features_customer_date', 'feature_snapshots', ['customer_id', 'snapshot_date'], unique=False)
    op.create_table('loans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('product_type', sa.String(length=30), nullable=False),
    sa.Column('principal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=False),
    sa.Column('emi_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('outstanding', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('active','closed','defaulted')", name='ck_loans_status'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_loans_customer_status', 'loans', ['customer_id', 'status'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('product_type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.Column('cbs_score', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('cbs_components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('constraints_passed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('constraints_failed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('shap_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('simulation_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('distress_probability', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('confidence_level', sa.String(length=25), nullable=False),
    sa.Column('confidence_interval', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('veto_reason', sa.String(length=100), nullable=True),
    sa.Column('llm_explanation', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('recommended','vetoed','no_action')", name='ck_recommendations_status'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recs_customer_created', 'recommendations', ['customer_id', 'created_at'], unique=False)
    op.create_table('recurring_obligations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('frequency', sa.String(length=10), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('linked_loan_id', sa.UUID(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("frequency IN ('monthly','quarterly','annual')", name='ck_obligations_frequency'),
    sa.CheckConstraint("type IN ('emi','rent','insurance_premium','sip','subscription')", name='ck_obligations_type'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['linked_loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_obligations_customer_active', 'recurring_obligations', ['customer_id', 'active'], unique=False)
    op.create_table('simulation_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=True),
    sa.Column('scenario', sa.String(length=50), nullable=False),
    sa.Column('n_paths', sa.Integer(), nullable=False),
    sa.Column('months_projected', sa.Integer(), nullable=False),
    sa.Column('p_shortfall_12m', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('expected_liquidity', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('liquidity_percentiles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sim_customer_created', 'simulation_results', ['customer_id', 'created_at'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('txn_time', sa.Time(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('type', sa.String(length=6), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('merchant', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('recurring_id', sa.UUID(), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=True),
    sa.Column('anomaly_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("type IN ('credit','debit')", name='ck_transactions_type'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['recurring_id'], ['recurring_obligations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_txns_anomalies', 'transactions', ['customer_id'], unique=False)
    op.create_index('idx_txns_customer_category', 'transactions', ['customer_id', 'category'], unique=False)
    op.create_index('idx_txns_customer_date', 'transactions', ['customer_id', 'txn_date'], unique=False)
    op.create_index('idx_txns_customer_recurring', 'transactions', ['customer_id', 'is_recurring'], unique=False)
    op.create_table('anomalies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('detection_method', sa.String(length=20), nullable=False),
    sa.Column('anomaly_score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.Column('is_true_positive', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_anomalies_customer_detected', 'anomalies', ['customer_id', 'detected_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_anomalies_customer_detected', table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index('idx_txns_customer_recurring', table_name='transactions')
    op.drop_index('idx_txns_customer_date', table_name='transactions')
    op.drop_index('idx_txns_customer_category', table_name='transactions')
    op.drop_index('idx_txns_anomalies', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('idx_sim_customer_created', table_name='simulation_results')
    op.drop_table('simulation_results')
    op.drop_index('idx_obligations_customer_active', table_name='recurring_obligations')
    op.drop_table('recurring_obligations')
    op.drop_index('idx_recs_customer_created', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index('idx_loans_customer_status', table_name='loans')
    op.drop_table('loans')
    op.drop_index('idx_features_customer_date', table_name='feature_snapshots')
    op.drop_table('feature_snapshots')
    op.drop_index('idx_consent_customer_scope', table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_index('idx_audit_customer_ts', table_name='audit_logs')
    op.drop_index('idx_audit_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('idx_customers_persona', table_name='customers')
    op.drop_table('customers')
    op.drop_index('idx_bank_products_type', table_name='bank_products')
    op.drop_table('bank_products')
    # ### end Alembic commands ###
